### ISSUE TITLE
AI should not attempt to fire a range attack without blowthrough if there's someone in the way

### ISSUE THREAD

**Issue by thejoshwolfe** [thejoshwolfe/legend-of-swarkland#33]
this applies to throwing potions, zapping or casting magic bullet, and spitting blinding venom. if there's someone in the way, it's not going to turn out the way you want.

**Comment by 1-800-thewolf** [comment]
You could have it based on the intelligence of the monster. Maybe a lich king's smart enough to know they'll hit the wrong thing but a lightning elemental might just instinctively attack anyway
