### ISSUE TITLE
"use ability" menu when polymorphed into a tar elemental shows the scorpion image

### ISSUE THREAD

**Issue by andrewrk** [thejoshwolfe/legend-of-swarkland#37]
![screenshot_2016-12-07_22-37-33](https://cloud.githubusercontent.com/assets/106511/20996738/c4e71c9c-bccd-11e6-82bd-19eb39971f0b.png)

**Comment by thejoshwolfe** [comment]
that's actually a cobra, but yeah. i still need to update that menu. I'll probably just show a tar elemental instead.
