### ISSUE TITLE
practice skills instead of experience for kills

### ISSUE THREAD

**Issue by thejoshwolfe** [thejoshwolfe/legend-of-swarkland#40]
# Skills

Currently, you level up by being responsible for the deaths of others. Leveling up increases your hitpoints, your attack damage, and your mana capacity. Despite being a standard trope of RPGs, this doesn't make a whole lot of sense.

Proposal:

1. Get rid of general XP and XP levels.
2. Introduce experience and levels for specific things, which we could call "skills": HP, MP, attack damage, other new stuff as needed. You gain experience in a skill by using it, which is different for each skill. At predetermined checkpoints in your leveling up (also dependent on the skill), you level up in that skill. All skills start at level 0, and the maximum level for a skill is something like 6.
3. When you polymorph, you retain your skill levels, although every species has a different base value for every skill. The base HP of an ant is much lower than the base HP of a dragon, so even if you retain your HP level 6 when polymorphing between species, your HP can still go up and down wildly.
4. We still need some general sense of monster difficulty for the sake of generating monsters on levels. This can be determined simply by the monster's species.

Specific skill mechanics:

* *HP*: practice this skill by getting hurt. your HP level gives you bonus HP = `HP_level * 0.2 * base_HP` or something.
* *MP*: practice this skill by attempting to cast spells from spell books (failed attempts still count).
* *attack damage*: practice this skill by attacking enemies. killing is not necessary.

# Tiered skill practice

The above proposal leads to some tempting grinding, so there is a follow up proposal that attempts to address this.

Proposal:

For every skill, there's a difficulty rating on the practice you can get for it. For combat skills, this is the difficulty of the monster you're engaging. There's a limited amount of practice you can gain from easy practice.; eventually, you have to practice on harder challenges.

Practice is not a simple scalar, like XP is in most RPGs (and like it is in swarkland currently). There are multiple buckets of experience you can fill; each bucket has an associated difficulty and a limit to how much practice it can hold. The easiest bucket is very small, only allowing, say, 5 practice points. The more difficult the bucket, the higher capacity it has for holding practice points.

When you gain a practice point with an associated difficulty, it attempts to go into the bucket with the associated difficulty. If that bucket is full, it tries the next lowest difficulty, and so on. If all buckets are full at and below the difficulty associated with the practice point, the practice is wasted.

When skills level up is determined by the scalar milestones reached from the sum total of practice points from buckets of all difficulty levels. The first level up might be at 5 total points across all the buckets. The next may be at 15 practice points, and so on.

With this proposal, you are never punished for practicing with harder challenges, but your are eventually punished (or rather no longer rewarded) for practicing on challenges that are too easy.

**Comment by andrewrk** [comment]
I'm a big fan of this idea.

One thing I would add is that it should be transparent to the player how this mechanism works. The system makes sense, but without some kind of visualization of the bucket system, players might not understand how leveling up works. Is discovering how it works part of the fun? Nethack would say yes. Swarkland perhaps might say no, that's a cheap way to make fun and swarkland is trying to achieve deeper fun by making the mechanisms of the game transparent but put the player in delightfully surprising or complex situations within those understood mechanisms.

**Comment by thejoshwolfe** [comment]
I've got a short-term plan, a mid-term plan, and a long-term plan for conveying the information to the player.

1. short-term plan: put a link in the readme to this issue where the mechanics are described in some kind of detail. In other words, do nothing. :)
2. mid-term plan: click on the status bar at the bottom to open a view with complete information.
3. long-term plan: the grand encyclopedia plan. have the display of information evolve as you play the game, and all that.

I definitely want the player to get all the information they could ever want through some fair in-game mechanics. I'm not interested in hiding the mysteries of the game engine (remember that it's open source after all). The swarkland philosophy is that any game that encourages players to use a 3rd-party wiki to learn about the game is an incomplete game.
