### ISSUE TITLE
don't delete save file on death

### ISSUE THREAD

**Issue by thejoshwolfe** [thejoshwolfe/legend-of-swarkland#47]
Not only does it make it hard to find bugs that result in you dying, it's also probably not what we want long term anyway. We should rename the file to get it out of the way of the default save location (so that relaunching the game starts a new game), but keep it around with some name that has a timestamp in it or something. or maybe just sequential indexes, idk.

we should also rename your file out of the way when you "win" by defeating the lich king, because you probably want to start a new game if you start the game again after that.

**Comment by andrewrk** [comment]
I would like to point out that a save file is proof of a score or a victory if you win. One can run a save file through a trusted swarkland build and determine if it is a fair and valid victory.

**Comment by thejoshwolfe** [comment]
That would not detect save scumming, but it would detect hacking and cheatcodes. in order to ensure no save scumming, you'd need a server that keeps the player behind the network protocol, and also #2.
