### ISSUE TITLE
How do you kill the rhino?

### ISSUE THREAD

**Issue by dbandstra** [thejoshwolfe/legend-of-swarkland#54]
I can't get past the room with the rhino and a goblin.

**Comment by thejoshwolfe** [comment]
yep. that's the final level for a reason. it's really hard.

for the long-term plan for this game, nothing that difficult should ever be required. pulling off a goblin-rhino kill with no equipment (equipment isn't implemented yet.) would be an extreme conduct strategy, not something a typical player would need to do.

at this stage in the game, the linear progression of puzzles is all there is to the game, and it *is* possible to kill a rhino with just a goblin, so i put that puzzle in as the final challenge.

also thanks for playing and giving feedback! if you really want to know the solution, there's a hotkey to enter "beat the level" input macros if you begin a new game and press shift+`}`. that is obviously a cheatcode and not the intended way to play the game. the sequence of inputs to beat the final level starts here: https://github.com/thejoshwolfe/legend-of-swarkland/blob/7de088739ce77521912b0e204a572b9cb0a28ffa/src/client/game_engine_client.zig#L412

**Comment by dbandstra** [comment]
Thanks :) I'm eager to try this out at home.

The previous rooms with turtles and rhinos were pretty fun, especially the one with rhino and lava. I like the game concept.

**Comment by dbandstra** [comment]
Ah! I didn't realize you could go through the rhino head on!

BTW I like the graphics too, reminds me of Exile: Escape from the Pit which I played as a kid.

**Comment by thejoshwolfe** [comment]
going through the rhino is not necessary. you can also just step to the side.

entities swapping places when moving toward each other will probably be revisited someday. it seems like that shouldn't work. but idk; maybe it's more interesting if it stays in the game?

the graphics are mostly lifted from: https://opengameart.org/content/dungeon-crawl-32x32-tiles

**Comment by andrewrk** [comment]
wat you can go through the rhino?
