### ISSUE TITLE
Game window is bigger than screen

### ISSUE THREAD

**Issue by jorgejarai** [thejoshwolfe/legend-of-swarkland#8]
When I executed the game, for the first time, I realized that the game window is bigger than my 1366x768 screen.

**Comment by thejoshwolfe** [comment]
yeah. sorry. a lot of people have this problem.

I'm thinking we might want the ability to scroll the main map area.

Another idea is to zoom out, which would distort the 32x32 sprites a little bit.

Another idea is to actually make the world smaller, but I don't like this idea very much.

**Comment by 1-800-thewolf** [comment]
Why not just zoom out and scale to the size of the screen for now. It would allow more people to play it and still have the same general experience. Maybe a more permanent solution (which allows for larger levels as well) is to allow it to scroll but that sounds more difficult to implement.

**Comment by andrewrk** [comment]
I have the opposite problem:
![screenshot_2016-12-07_22-15-49](https://cloud.githubusercontent.com/assets/106511/20996328/d01b045a-bcca-11e6-81fc-c9db6e38cafa.png)

The game window is so small that the text is unreadable on my high DPI display.

**Comment by thejoshwolfe** [comment]
master now does crude scaling to fit the window size. Growing the window size looks pretty decent. Reducing the window size makes the text pretty hard to read. Not sure what to do about that in the future, but for now, I'm calling this issue resolved.

![screenshot](https://cloud.githubusercontent.com/assets/87436/21161650/abb199aa-c146-11e6-8c45-37191c3208c2.png)
